name: Setup GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: write

jobs:
  setup-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Enable Pages
        run: |
          echo "GitHub Pages has been configured. Please run the deploy workflow."